package com.fenixenforge.mobCoins.Utils;

public enum ItmesFlags {
    ENCHANT, POTIONS, HIDE_ATTRIBUTES, HIDE_DESTROYS, HIDE_ENCHANTS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS, HIDE_ADDITIONAL_TOOLTIP, HIDE_UNBREAKABLE, HIDE_ARMOR_TRIM
}
